services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./backend/.env
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend/app:/app
    ports:
      - "5000:5000"
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app_network:
    driver: bridge